<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.ui.testautomation.CovidIndiaUITest" tests="6" time="172.568" ignored="0" failures="1" timestamp="17 Apr 2020 20:49:18 GMT" skipped="1" hostname="RANADEEP_BANIK" errors="0">
  <testcase name="checkCaseCalculationsOfTripuraIsGreaterThan10" time="5.595" classname="com.ui.testautomation.CovidIndiaUITest">
    <skipped/>
  </testcase> <!-- checkCaseCalculationsOfTripuraIsGreaterThan10 -->
  <testcase name="checkCaseCalculationsOfTripuraIsGreaterThan10" time="14.704" classname="com.ui.testautomation.CovidIndiaUITest">
    <failure type="java.lang.AssertionError" message="Case count is not greater than 10 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Case count is not greater than 10 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.app.testautomation.utilities.Assertions.assertTrue(Assertions.java:24)
	at com.ui.testautomation.CovidIndiaUITest.checkCaseCalculationsOfTripuraIsGreaterThan10(CovidIndiaUITest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
    </failure>
  </testcase> <!-- checkCaseCalculationsOfTripuraIsGreaterThan10 -->
  <testcase name="checkNoOfConfirmedCasesIsGreaterThan6000" time="16.433" classname="com.ui.testautomation.CovidIndiaUITest"/>
  <testcase name="checkCaseCalculationsForAllStates" time="92.989" classname="com.ui.testautomation.CovidIndiaUITest"/>
  <testcase name="checkCaseCalculationsForChandigarh" time="16.207" classname="com.ui.testautomation.CovidIndiaUITest"/>
  <testcase name="checkCaseCalculationsForDelhi" time="26.640" classname="com.ui.testautomation.CovidIndiaUITest"/>
</testsuite> <!-- com.ui.testautomation.CovidIndiaUITest -->
